server:
    port: 9001
spring:
    application:
        name: cloud-alibaba-user-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/xdclass?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: nrblwbb7
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                namespace: 3265aa65-dbbc-4d24-856f-bf5ab9b82e5f
        sentinel:
            transport:
                # 控制台ip
                dashboard: 127.0.0.1:8080
                # 不能被占用的随机端口，与sentinel交互的端口
                port: 9997

mybatis:
    configuration:
#        sql-fragments: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true  # 驼峰命名